### PR TITLE
Allows selection of any existing highlight group for highlighting

### PR DESCRIPTION
**Pull request by jam1015**
Added code to let the user select any highlight group for use with highlight on yank/put.

Added documentation to `README.md` but not to the actual documentation text file because my understanding is that changes to the readme are automatically incorporated into the help documentation when committed to main.

### CODE REVIEW

**Comment by gbprod** [comment]
Hi and thanks for this pull request!

However, I think this change is not necessary because it is possible to change the highlight group using default neovim API :

```lua
vim.api.nvim_set_hl(0, "YankyPut", { link = "MyCustomHighlightGroup" })
vim.api.nvim_set_hl(0, "YankyYanked", { link = "MyOtherCustomHighlightGroup" })
```

**Comment by jam1015** [comment]
Hi! Thanks for the feedback. You probably are worried about pull requests like this making your code bloated or unmanageable. You're right that the API calls you mention do the same thing as my pull request.

Neovim is unique because it's more of a DIY kit than a finished product.  The user is better off having some knowledge of programming to be able to turn it into a powerful tool. However even among people who know lua/vimscript there is a distribution of abilities; plugin authors like you have a comprehensive knowledge of the API, etc; others, 'advanced beginners' such as myself only know enough lua/vimscript to configure neovim rather than develop for it.  

This particular API call you suggest is something that a very advanced user would know immediately.  However, when you say 'You can override the `YankyPut` and yanky `YankyYanked` highlight groups to change colors.' in the documentation I had no idea what you were referring to until your examples in this PR. I think many other advanced beginners would agree. 

 The `setup` function is the intended place for plugin configuration, so relying on it leads to a cleaner configuration, with much less mental effort. When these highlight options are added to the default lua table that is passed to the `setup` function the plugin is more self-documenting. 

If you disagree with me I have a separate branch that I can do a PR on that gives explicit examples of using the `vim.api.nvim_set_hl` function in `README.md` to help users who aren't as familiar with the API as you are.

**Comment by gbprod** [comment]
Hey!
I'm not sure that this plugin is the place to re-document the Neovim API. I agree that Neovim is a kind of DIY kit, and it's his strength. However, I think, `vim.api.nvim_set_hl` is something really basic and you don't need to be an advanced user to know this. 
Maybe just a link to the Neovim documentation of `vim.api.nvim_set_hl` or `:h nvim_set_hl()` should be enought.

**Comment by jam1015** [comment]
It may be the case that your experience as an advanced user biases you regarding what you think is advanced. But maybe you're right. You are right that having a link to nvim's documentation would improve the existing documentation.

But I would also argue that `vim.api.nvim_set_hl` is one level too low that someone should have to go to configure a plugin.  The proper/intended place to configure a lua plugin is in the `setup` function so to me it makes sense to put as much configuration there as possible, which is what this PR aims for. But again, linking to the documentation of `nvim_set_hl` is an adequate fix. 

I'll leave it at that, let you decide what to do. Thanks for writing a great plugin!

**Comment by gbprod** [comment]
Thanks for your feedback, I'll probably add something in the Readme about that ;)

**Pull request closed without merging**
